#!/usr/bin/python

import os, sys, platform, shutil

def rmtreeOnError(func, path, exc_info):
    print "Error removing " + path

def main():
    AgentLaunchdPlist="/Library/LaunchAgents/com.delicioussafari.DeliciousSafariAgent.plist"
    
    user = os.getenv("USER")
    print "Loading launchd plist for user " + user
    launchdCommand="sudo -u '%s' launchctl load -S Aqua '%s'" % (os.getenv("USER"), AgentLaunchdPlist)
    os.system(launchdCommand)

    sys.exit(0)

main()
